[package]
authors = ["Hugo Ledoux <h.ledoux@tudelft.nl>"]
name    = "startin"
version = "0.4.6"
edition = "2018"


[dependencies]
startin = "0.4.6"


[dependencies.pyo3]
version = "0.8.2"
features = ["extension-module"]

[lib]
name = "startin"
crate-type = ["cdylib"]
