name: Build Python bindings

on:
  push:
  pull_request:

jobs:
  Windows:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu]
        include:
          - python-version: "3.10"
            os: windows
          - python-version: "3.10"
            os: macos

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - if: matrix.os == 'macos'
      name: Install aarch64-apple-darwin toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
    - if: matrix.os != 'macos'
      uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: build
        manylinux: auto
        args: --release --no-sdist
    - if: matrix.os == 'macos'
      uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: build
        args: --release --no-sdist --universal2
