name: Build Python bindings

on:
 release:
  types: [created]

jobs:
  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install maturin
    - name: Do the work mate
      run: maturin publish -i python --no-sdist -u hledoux -p ${{ secrets.PASSWORD_PYPI }}

  macOS:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install aarch64-apple-darwin toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
    - name: Install dependencies
      run: pip install maturin
    - name: Do the work mate
      run: maturin publish -i python --no-sdist --universal2 -u hledoux -p ${{ secrets.PASSWORD_PYPI }}

  Linux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_24_x86_64
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install maturin
    - name: Do the work mate
      run: maturin publish -i python -u hledoux -p ${{ secrets.PASSWORD_PYPI }}
