name: Publish Python bindings

on:
 release:
  types: [created]

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: publish
        args: --no-sdist -u hledoux -p ${{ secrets.PASSWORD_PYPI }}

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install aarch64-apple-darwin toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: publish
        args: --no-sdist --universal2 -u hledoux -p ${{ secrets.PASSWORD_PYPI }}

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: publish
        args: --no-sdist -u hledoux -p ${{ secrets.PASSWORD_PYPI }}
